name: influ CI

on: push

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'
      - run: flutter pub get
      - run: flutter test

  # e2e_test:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-java@v2
  #       with:
  #         distribution: 'zulu'
  #         java-version: '11'
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         flutter-version: '2.5.3'
  #     - run: xcrun simctl list --json devices available
  #     - run: flutter pub get
  #     - run: flutter doctor
  #     - run: flutter devices
  #     - uses: futureware-tech/simulator-action@v1
  #       with:
  #         model: 'iPhone 12'
  #     - run: flutter doctor
  #     - run: flutter devices
  #     - run: dart --verbose test_driver/app_test.dart
  drive_browser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      #- uses: browser-actions/setup-chrome@latest
      - uses: subosito/flutter-action@v1
      - run: flutter doctor
      - run: flutter config --enable-web  
      - run: chromedriver --version  
      - run: flutter pub get
      # - run: chromedriver --port=4444 --disable-gpu  
      - run: chromedriver --port=4444 & sleep 1000 & flutter drive --verbose -d web-server --headless --target=test_driver/app.dart 

  drive_ios:
    strategy:
      matrix:
        device:
          - "iPhone 11 Pro (14.4)"
      fail-fast: false
    runs-on: macos-latest
    steps:
      - name: List all simulators
        run: xcrun instruments -s
      # get UUID  simulator and boot a simulator on mac from  command line
      - name: Start Simulator
        run: |
          UDID=$(
            xcrun instruments -s |
            awk \
              -F ' *[][]' \
              -v 'device=${{ matrix.device }}' \
              '$1 == device { print $2 }'
          )
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'
      - run: flutter pub get
      - run: flutter devices
      - run: flutter drive --verbose --target=test_driver/app.dart

  drive_android:
    runs-on: macos-latest
    #creates a build matrix for your jobs
    strategy:
      #set of different configurations of the virtual environment.
      matrix:
        api-level: [29]
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'
      - run: flutter pub get
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: |
            flutter devices
            flutter drive --verbose --target=test_driver/app.dart
